Style homepage
Lelberto/drawtheyear-frontend pull request #4
Opened 2021-02-13 13:16 UTC by Faichyer

Here are the changes: 

- Background color is now a radial gradient
- Added a new font : Quicksand [300, 700] 
- Animation in component `Squares() `
- Footer stuck at bottom 
- Welcome message

2021-02-13 14:43 UTC, Rocknologie reviewed
Les polices d'écritures elles vont pas dans le gitinore ??

2021-02-13 14:43 UTC, Rocknologie commented on src/assets/css/app.css
> +.squares li{
Toutes les balises 'squares' c'est pour du responsive ?

2021-02-13 14:43 UTC, Rocknologie commented on src/components/home/squares.tsx
> +        <li></li>
C'est en attente d'optimisation les balises li ?

2021-02-13 22:12 UTC, Faichyer commented on src/components/home/squares.tsx
> +        <li></li>
Ouais mais je sais pas faire :/

2021-02-13 22:12 UTC, Faichyer commented on src/assets/css/app.css
> +.squares li{
Nope c'est les carrés qui flottent

2021-02-13 22:13 UTC, Faichyer commented
> Les polices d'écritures elles vont pas dans le gitinore ??

Non c'est un asset

2021-02-14 12:26 UTC, Lelberto requested changes
Y'a un problème sur le footer qui est pas centré et y'a un slider horizontal 😢
![image](https://user-images.githubusercontent.com/39899748/107876709-e1286400-6ec7-11eb-9b18-a99b7a7f4182.png)


Et le footer est en position statique ?
![image](https://user-images.githubusercontent.com/39899748/107876766-39f7fc80-6ec8-11eb-9750-9a78e5737bf0.png)

2021-02-14 12:30 UTC, Faichyer commented
Y a un bug gros 😂 
Je regarde ce soir

2021-02-14 13:33 UTC, Faichyer commented
Ok ouais

2021-02-16 09:58 UTC, Rocknologie approved these changes

2021-02-16 13:21 UTC, Faichyer reviewed
Nice

2021-02-16 13:22 UTC, Lelberto requested changes
Jolie scrollbar bg mais le footer est toujours éclaté
![image](https://user-images.githubusercontent.com/39899748/108068014-db668600-7061-11eb-97dd-7312931c34b6.png)

2021-02-16 13:22 UTC, Lelberto commented on src/assets/css/app.css
> +}
Manque la ligne end of file

2021-02-16 13:22 UTC, Lelberto commented on src/components/home/home-page.tsx
> +    <div className="container mx-auto sidebar-styled">
Peut-être renommer la classe `sidebar` en `scrollbar` pour pas se paumer

2021-02-17 22:27 UTC, Lelberto approved these changes
C'est du bon travail enculé

2021-02-17 22:27 UTC, merged